name: pre-commit hooks check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
    - id: changed-files
      uses: tj-actions/changed-files@v41
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}
