name: "Run FlowBlot.NET"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/benchmarks/FlowBlot/bootstrap.sh'
      - 'scripts/benchmarks/FlowBlot/run.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scripts/benchmarks/FlowBlot/bootstrap.sh'
      - 'scripts/benchmarks/FlowBlot/run.sh'
  workflow_dispatch:

env:
  BENTOO_SCRIPT: "./scripts/bentoo.sh"
  BENCHMARK_NAME: "FlowBlot.NET"
  RUN_BENCHMARK_SCRIPT: "./scripts/benchmarks/FlowBlot/run.sh"
  RUN_BENCHMARK_OUTPUT: "FlowBlot.NET-output"
  BOOTSTRAP_SCRIPT: "./scripts/benchmarks/FlowBlot/bootstrap.sh"

jobs:
  reference_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install python requirements
      run: pip install -r ./requirements.txt

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Bootstrap
      run: |
        ${{ env.BOOTSTRAP_SCRIPT }} --exit-on-error
        ${{ env.BENTOO_SCRIPT }}

    - name: Reference run
      shell: bash
      run: ${{ env.RUN_BENCHMARK_SCRIPT }}

    - name: Archive output
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.BENCHMARK_NAME }}-output"
        path: ${{ env.RUN_BENCHMARK_OUTPUT }}
