name: "Run BenchmarkJava-mutated"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/benchmarks/BenchmarkJava/bootstrap-mutated.sh'
      - 'scripts/benchmarks/BenchmarkJava/run-mutated.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scripts/benchmarks/BenchmarkJava/bootstrap-mutated.sh'
      - 'scripts/benchmarks/BenchmarkJava/run-mutated.sh'
  workflow_dispatch:

env:
  BENTOO_SCRIPT: "./scripts/bentoo.sh"
  BENCHMARK_NAME: "BenchmarkJava-mutated"
  RUN_BENCHMARK_SCRIPT: "./scripts/benchmarks/BenchmarkJava/run-mutated.sh"
  RUN_BENCHMARK_OUTPUT: "BenchmarkJava-mutated-output"
  BOOTSTRAP_SCRIPT: "./scripts/benchmarks/BenchmarkJava/bootstrap-mutated.sh"
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  reference_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Python requirements
      run: pip install -r ./requirements.txt

    - name: Install Java
      run: |
        sudo apt-get update
        sudo apt-get install -y -q --no-install-recommends \
          git \
          maven
        wget https://download.oracle.com/java/22/archive/jdk-22.0.1_linux-x64_bin.deb -O jdk-22.0.1_linux-x64_bin.deb
        sudo dpkg -i jdk-22.0.1_linux-x64_bin.deb

    - name: Bootstrap
      run: |
        export VULNOMICON_JAVA_HOME_22=/usr/lib/jvm/jdk-22-oracle-x64/
        ${{ env.BOOTSTRAP_SCRIPT }} --exit-on-error
        ${{ env.BENTOO_SCRIPT }}

    - name: Reference run
      shell: bash
      run: |
        export VULNOMICON_JAVA_HOME_22=/usr/lib/jvm/jdk-22-oracle-x64/
         ${{ env.RUN_BENCHMARK_SCRIPT }}

    - name: Archive output
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.BENCHMARK_NAME }}-output"
        path: ${{ env.RUN_BENCHMARK_OUTPUT }}
