name: "Run skf-labs-python-mutated"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/benchmarks/skf-labs/bootstrap-mutated.sh'
      - 'scripts/benchmarks/skf-labs/python/run-mutated.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scripts/benchmarks/skf-labs/bootstrap-mutated.sh'
      - 'scripts/benchmarks/skf-labs/python/run-mutated.sh'
  workflow_dispatch:

env:
  BENTOO_SCRIPT: "./scripts/bentoo.sh"
  BENCHMARK_NAME: "skf-labs-python-mutated"
  RUN_BENCHMARK_SCRIPT: "./scripts/benchmarks/skf-labs/python/run-mutated.sh"
  RUN_BENCHMARK_OUTPUT: "skf-labs-python-mutated-output"
  BOOTSTRAP_SCRIPT: "./scripts/benchmarks/skf-labs/bootstrap-mutated.sh"
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  reference_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install python requirements
      run: pip install -r ./requirements.txt

    - name: Bootstrap
      run: |
        ${{ env.BOOTSTRAP_SCRIPT }} --exit-on-error
        ${{ env.BENTOO_SCRIPT }}

    - name: Reference run
      shell: bash
      run: ${{ env.RUN_BENCHMARK_SCRIPT }}

    - name: Archive output
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.BENCHMARK_NAME }}-output"
        path: ${{ env.RUN_BENCHMARK_OUTPUT }}
