name: "Run BenchmarkJava-mutated"

on:
  push:
    branches: [ "main" ]
    paths:
      - './scripts/bootstrap-BenchmarkJava-mutated.sh'
      - './scripts/runBenchmarkJavaMutated.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - './scripts/bootstrap-BenchmarkJava-mutated.sh'
      - './scripts/runBenchmarkJavaMutated.sh'
  workflow_dispatch:

env:
  BENTOO_SCRIPT: "./scripts/bentoo.sh"
  BENCHMARK_NAME: "BenchmarkJava-mutated"
  RUN_BENCHMARK_SCRIPT: "./scripts/runBenchmarkJavaMutated.sh"
  RUN_BENCHMARK_OUTPUT: "BenchmarkJava-mutated-output"
  BOOTSTRAP_SCRIPT: "./scripts/bootstrap-BenchmarkJava-mutated.sh"

jobs:
  reference_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install python requirements
      run: pip install -r ./requirements.txt

    - name: Install Java
      run: |
        sudo apt-get update
        sudo apt-get install -y -q --no-install-recommends \
          git \
          openjdk-11-jdk \
          openjdk-11-jre-headless \
          maven

    - name: Bootstrap
      run: |
        export VULNOMICON_JAVA_HOME_11=/usr/lib/jvm/java-11-openjdk-amd64/
        ${{ env.BOOTSTRAP_SCRIPT }} --exit-on-error
        ${{ env.BENTOO_SCRIPT }}

    - name: Reference run
      shell: bash
      run: ${{ env.RUN_BENCHMARK_SCRIPT }}

    - name: Archive output
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.BENCHMARK_NAME }}-output"
        path: ${{ env.RUN_BENCHMARK_OUTPUT }}
